# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dbarison_curriculum}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Davide Barison"]
  s.date = %q{2010-03-04}
  s.default_executable = %q{dbarison}
  s.description = %q{Get Davide Barison's Curriculm Vitae typing 'dbarison' from your terminal}
  s.email = %q{davide@megiston.it}
  s.executables = ["dbarison"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/dbarison",
     "dbarison_curriculum.gemspec",
     "lib/dbarison_curriculum.rb",
     "test/helper.rb",
     "test/test_dbarison_curriculum.rb"
  ]
  s.homepage = %q{http://github.com/dbarison/epilotto_curriculum}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Davide Barison's Curriculm Vitae}
  s.test_files = [
    "test/helper.rb",
     "test/test_dbarison_curriculum.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
  end
end

